@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AppParser" as AddressBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
end box

[-> LogicManager : execute("edit --application 1 --name Jay --title SWE")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit --application 1 --name Jay --title SWE")
activate AddressBookParser

create EditCommandParser
AddressBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> AddressBookParser
deactivate EditCommandParser

AddressBookParser -> EditCommandParser : parse("--application 1 --name Jay --title SWE")
activate EditCommandParser

EditCommandParser -> EditCommandParser : validateFlags()

EditCommandParser --> AddressBookParser : d
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> AddressBookParser
destroy EditCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser


[<--LogicManager
deactivate LogicManager
@enduml
