title: "Jobby"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

kramdown:
  toc_levels: "2,3,4"

repository: "ay2324s1-cs2103t-w08-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
